import { IRootCompetition } from "../@types/competition";
import { ICompetitionScorers } from "../@types/competition_scorers";
import { ICompetitionStandings } from "../@types/competition_standings";
import { ITeam } from "../@types/team";

export class DataFake {
  /**
   *
   *
   * @static
   * @return {*}  {IRootCompetition}
   * @memberof DataFake
   */
  static CompetitionsAreas(): IRootCompetition {
    return {
      count: 13,
      filters: {
        client: "Minh Nguyen",
      },
      competitions: [
        {
          id: 2013,
          area: {
            id: 2032,
            name: "Brazil",
            code: "BRA",
            flag: "https://crests.football-data.org/764.svg",
          },
          name: "Campeonato Brasileiro Série A",
          code: "BSA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/764.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1377,
            startDate: "2022-04-10",
            endDate: "2022-11-13",
            currentMatchday: 38,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2021-07-20T18:42:17Z",
        },
        {
          id: 2016,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Championship",
          code: "ELC",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ELC.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1502,
            startDate: "2022-07-29",
            endDate: "2023-05-06",
            currentMatchday: 23,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2022-03-20T09:31:30Z",
        },
        {
          id: 2021,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1490,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 17,
            winner: null,
          },
          numberOfAvailableSeasons: 124,
          lastUpdated: "2022-03-20T08:58:54Z",
        },
        {
          id: 2001,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "UEFA Champions League",
          code: "CL",
          type: "CUP",
          emblem: "https://crests.football-data.org/CL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1491,
            startDate: "2022-06-21",
            endDate: "2023-06-10",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 43,
          lastUpdated: "2022-03-20T09:20:44Z",
        },
        {
          id: 2018,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "European Championship",
          code: "EC",
          type: "CUP",
          emblem: "https://crests.football-data.org/EUR.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1537,
            startDate: "2024-06-14",
            endDate: "2024-07-14",
            currentMatchday: 1,
            winner: null,
          },
          numberOfAvailableSeasons: 17,
          lastUpdated: "2021-07-20T18:34:04Z",
        },
        {
          id: 2015,
          area: {
            id: 2081,
            name: "France",
            code: "FRA",
            flag: "https://crests.football-data.org/773.svg",
          },
          name: "Ligue 1",
          code: "FL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/FL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1497,
            startDate: "2022-08-07",
            endDate: "2023-06-03",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 79,
          lastUpdated: "2022-03-20T09:30:02Z",
        },
        {
          id: 2002,
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          name: "Bundesliga",
          code: "BL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/BL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1495,
            startDate: "2022-08-05",
            endDate: "2023-05-27",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 60,
          lastUpdated: "2022-03-20T08:52:53Z",
        },
        {
          id: 2019,
          area: {
            id: 2114,
            name: "Italy",
            code: "ITA",
            flag: "https://crests.football-data.org/784.svg",
          },
          name: "Serie A",
          code: "SA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/SA.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1505,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 91,
          lastUpdated: "2022-03-20T09:16:43Z",
        },
        {
          id: 2003,
          area: {
            id: 2163,
            name: "Netherlands",
            code: "NLD",
            flag: "https://crests.football-data.org/8601.svg",
          },
          name: "Eredivisie",
          code: "DED",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ED.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1494,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 67,
          lastUpdated: "2022-03-20T09:19:27Z",
        },
        {
          id: 2017,
          area: {
            id: 2187,
            name: "Portugal",
            code: "PRT",
            flag: "https://crests.football-data.org/765.svg",
          },
          name: "Primeira Liga",
          code: "PPL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PPL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1518,
            startDate: "2022-08-07",
            endDate: "2023-05-28",
            currentMatchday: 14,
            winner: null,
          },
          numberOfAvailableSeasons: 74,
          lastUpdated: "2022-03-20T09:34:09Z",
        },
        {
          id: 2152,
          area: {
            id: 2220,
            name: "South America",
            code: "SAM",
            flag: "https://crests.football-data.org/CLI.svg",
          },
          name: "Copa Libertadores",
          code: "CLI",
          type: "CUP",
          emblem: "https://native-stats.org/assets/flags/SAM.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 873,
            startDate: "2022-02-09",
            endDate: "2022-09-06",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 2,
          lastUpdated: "2022-10-31T15:20:09Z",
        },
        {
          id: 2014,
          area: {
            id: 2224,
            name: "Spain",
            code: "ESP",
            flag: "https://crests.football-data.org/760.svg",
          },
          name: "Primera Division",
          code: "PD",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PD.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1504,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 92,
          lastUpdated: "2022-03-20T09:20:08Z",
        },
        {
          id: 2000,
          area: {
            id: 2267,
            name: "World",
            code: "INT",
            flag: null,
          },
          name: "FIFA World Cup",
          code: "WC",
          type: "CUP",
          emblem: "https://crests.football-data.org/qatar.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1382,
            startDate: "2022-11-20",
            endDate: "2022-12-18",
            currentMatchday: 8,
            winner: null,
          },
          numberOfAvailableSeasons: 22,
          lastUpdated: "2022-05-09T19:45:29Z",
        },
      ],
    };
  }

  static CompetitionsStandings(): ICompetitionStandings {
    return {
      filters: {
        season: "2022",
      },
      area: {
        id: 2077,
        name: "Europe",
        code: "EUR",
        flag: "https://crests.football-data.org/EUR.svg",
      },
      competition: {
        id: 2001,
        name: "UEFA Champions League",
        code: "CL",
        type: "CUP",
        emblem: "https://crests.football-data.org/CL.png",
      },
      season: {
        id: 1491,
        startDate: "2022-06-21",
        endDate: "2023-06-10",
        currentMatchday: 6,
        winner: null,
      },
      standings: [
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_A",
          table: [
            {
              position: 1,
              team: {
                id: 113,
                name: "SSC Napoli",
                shortName: "Napoli",
                tla: "NAP",
                crest: "https://crests.football-data.org/113.svg",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 20,
              goalsAgainst: 6,
              goalDifference: 14,
            },
            {
              position: 2,
              team: {
                id: 64,
                name: "Liverpool FC",
                shortName: "Liverpool",
                tla: "LIV",
                crest: "https://crests.football-data.org/64.png",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 17,
              goalsAgainst: 6,
              goalDifference: 11,
            },
            {
              position: 3,
              team: {
                id: 678,
                name: "AFC Ajax",
                shortName: "Ajax",
                tla: "AJA",
                crest: "https://crests.football-data.org/678.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 0,
              lost: 4,
              points: 6,
              goalsFor: 11,
              goalsAgainst: 16,
              goalDifference: -5,
            },
            {
              position: 4,
              team: {
                id: 5376,
                name: "Rangers FC",
                shortName: "Rangers",
                tla: "RAN",
                crest: "https://crests.football-data.org/5376.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 0,
              lost: 6,
              points: 0,
              goalsFor: 2,
              goalsAgainst: 22,
              goalDifference: -20,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_B",
          table: [
            {
              position: 1,
              team: {
                id: 503,
                name: "FC Porto",
                shortName: "Porto",
                tla: "FCP",
                crest: "https://crests.football-data.org/503.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 0,
              lost: 2,
              points: 12,
              goalsFor: 12,
              goalsAgainst: 7,
              goalDifference: 5,
            },
            {
              position: 2,
              team: {
                id: 851,
                name: "Club Brugge KV",
                shortName: "Club Brugge",
                tla: "CLU",
                crest: "https://crests.football-data.org/851.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 2,
              lost: 1,
              points: 11,
              goalsFor: 7,
              goalsAgainst: 4,
              goalDifference: 3,
            },
            {
              position: 3,
              team: {
                id: 3,
                name: "Bayer 04 Leverkusen",
                shortName: "Leverkusen",
                tla: "B04",
                crest: "https://crests.football-data.org/3.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 4,
              goalsAgainst: 8,
              goalDifference: -4,
            },
            {
              position: 4,
              team: {
                id: 78,
                name: "Club Atlético de Madrid",
                shortName: "Atleti",
                tla: "ATL",
                crest: "https://crests.football-data.org/78.svg",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 5,
              goalsAgainst: 9,
              goalDifference: -4,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_C",
          table: [
            {
              position: 1,
              team: {
                id: 5,
                name: "FC Bayern München",
                shortName: "Bayern",
                tla: "FCB",
                crest: "https://crests.football-data.org/5.svg",
              },
              playedGames: 6,
              form: null,
              won: 6,
              draw: 0,
              lost: 0,
              points: 18,
              goalsFor: 18,
              goalsAgainst: 2,
              goalDifference: 16,
            },
            {
              position: 2,
              team: {
                id: 108,
                name: "FC Internazionale Milano",
                shortName: "Inter",
                tla: "INT",
                crest: "https://crests.football-data.org/108.png",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 1,
              lost: 2,
              points: 10,
              goalsFor: 10,
              goalsAgainst: 7,
              goalDifference: 3,
            },
            {
              position: 3,
              team: {
                id: 81,
                name: "FC Barcelona",
                shortName: "Barça",
                tla: "FCB",
                crest: "https://crests.football-data.org/81.svg",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 1,
              lost: 3,
              points: 7,
              goalsFor: 12,
              goalsAgainst: 12,
              goalDifference: 0,
            },
            {
              position: 4,
              team: {
                id: 1881,
                name: "FC Viktoria Plzeň",
                shortName: "Viktoria Plzeň",
                tla: "PLZ",
                crest: "https://crests.football-data.org/1881.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 0,
              lost: 6,
              points: 0,
              goalsFor: 5,
              goalsAgainst: 24,
              goalDifference: -19,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_D",
          table: [
            {
              position: 1,
              team: {
                id: 73,
                name: "Tottenham Hotspur FC",
                shortName: "Tottenham",
                tla: "TOT",
                crest: "https://crests.football-data.org/73.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 2,
              lost: 1,
              points: 11,
              goalsFor: 8,
              goalsAgainst: 6,
              goalDifference: 2,
            },
            {
              position: 2,
              team: {
                id: 19,
                name: "Eintracht Frankfurt",
                shortName: "Frankfurt",
                tla: "SGE",
                crest: "https://crests.football-data.org/19.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 1,
              lost: 2,
              points: 10,
              goalsFor: 7,
              goalsAgainst: 8,
              goalDifference: -1,
            },
            {
              position: 3,
              team: {
                id: 498,
                name: "Sporting Clube de Portugal",
                shortName: "Sporting CP",
                tla: "SPO",
                crest: "https://crests.football-data.org/498.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 1,
              lost: 3,
              points: 7,
              goalsFor: 8,
              goalsAgainst: 9,
              goalDifference: -1,
            },
            {
              position: 4,
              team: {
                id: 516,
                name: "Olympique de Marseille",
                shortName: "Marseille",
                tla: "MAR",
                crest: "https://crests.football-data.org/516.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 0,
              lost: 4,
              points: 6,
              goalsFor: 8,
              goalsAgainst: 8,
              goalDifference: 0,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_E",
          table: [
            {
              position: 1,
              team: {
                id: 61,
                name: "Chelsea FC",
                shortName: "Chelsea",
                tla: "CHE",
                crest: "https://crests.football-data.org/61.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 1,
              lost: 1,
              points: 13,
              goalsFor: 10,
              goalsAgainst: 4,
              goalDifference: 6,
            },
            {
              position: 2,
              team: {
                id: 98,
                name: "AC Milan",
                shortName: "Milan",
                tla: "MIL",
                crest: "https://crests.football-data.org/98.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 1,
              lost: 2,
              points: 10,
              goalsFor: 12,
              goalsAgainst: 7,
              goalDifference: 5,
            },
            {
              position: 3,
              team: {
                id: 1877,
                name: "FC Red Bull Salzburg",
                shortName: "RB Salzburg",
                tla: "RBS",
                crest: "https://crests.football-data.org/1877.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 3,
              lost: 2,
              points: 6,
              goalsFor: 5,
              goalsAgainst: 9,
              goalDifference: -4,
            },
            {
              position: 4,
              team: {
                id: 755,
                name: "GNK Dinamo Zagreb",
                shortName: "Dinamo Zagreb",
                tla: "DIN",
                crest: "https://crests.football-data.org/755.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 1,
              lost: 4,
              points: 4,
              goalsFor: 4,
              goalsAgainst: 11,
              goalDifference: -7,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_F",
          table: [
            {
              position: 1,
              team: {
                id: 86,
                name: "Real Madrid CF",
                shortName: "Real Madrid",
                tla: "RMA",
                crest: "https://crests.football-data.org/86.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 1,
              lost: 1,
              points: 13,
              goalsFor: 15,
              goalsAgainst: 6,
              goalDifference: 9,
            },
            {
              position: 2,
              team: {
                id: 721,
                name: "RB Leipzig",
                shortName: "RB Leipzig",
                tla: "RBL",
                crest: "https://crests.football-data.org/721.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 0,
              lost: 2,
              points: 12,
              goalsFor: 13,
              goalsAgainst: 9,
              goalDifference: 4,
            },
            {
              position: 3,
              team: {
                id: 1887,
                name: "FK Shakhtar Donetsk",
                shortName: "Shaktar",
                tla: "SHD",
                crest: "https://crests.football-data.org/1887.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 3,
              lost: 2,
              points: 6,
              goalsFor: 8,
              goalsAgainst: 10,
              goalDifference: -2,
            },
            {
              position: 4,
              team: {
                id: 732,
                name: "Celtic FC",
                shortName: "Celtic",
                tla: "CEL",
                crest: "https://crests.football-data.org/732.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 2,
              lost: 4,
              points: 2,
              goalsFor: 4,
              goalsAgainst: 15,
              goalDifference: -11,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_G",
          table: [
            {
              position: 1,
              team: {
                id: 65,
                name: "Manchester City FC",
                shortName: "Man City",
                tla: "MCI",
                crest: "https://crests.football-data.org/65.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 2,
              lost: 0,
              points: 14,
              goalsFor: 14,
              goalsAgainst: 2,
              goalDifference: 12,
            },
            {
              position: 2,
              team: {
                id: 4,
                name: "Borussia Dortmund",
                shortName: "Dortmund",
                tla: "BVB",
                crest: "https://crests.football-data.org/4.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 3,
              lost: 1,
              points: 9,
              goalsFor: 10,
              goalsAgainst: 5,
              goalDifference: 5,
            },
            {
              position: 3,
              team: {
                id: 559,
                name: "Sevilla FC",
                shortName: "Sevilla FC",
                tla: "SEV",
                crest: "https://crests.football-data.org/559.svg",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 6,
              goalsAgainst: 12,
              goalDifference: -6,
            },
            {
              position: 4,
              team: {
                id: 1876,
                name: "FC København",
                shortName: "København",
                tla: "KOB",
                crest: "https://crests.football-data.org/1876.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 3,
              lost: 3,
              points: 3,
              goalsFor: 1,
              goalsAgainst: 12,
              goalDifference: -11,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_H",
          table: [
            {
              position: 1,
              team: {
                id: 1903,
                name: "Sport Lisboa e Benfica",
                shortName: "SL Benfica",
                tla: "BEN",
                crest: "https://crests.football-data.org/1903.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 2,
              lost: 0,
              points: 14,
              goalsFor: 16,
              goalsAgainst: 7,
              goalDifference: 9,
            },
            {
              position: 2,
              team: {
                id: 524,
                name: "Paris Saint-Germain FC",
                shortName: "PSG",
                tla: "PSG",
                crest: "https://crests.football-data.org/524.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 2,
              lost: 0,
              points: 14,
              goalsFor: 16,
              goalsAgainst: 7,
              goalDifference: 9,
            },
            {
              position: 3,
              team: {
                id: 109,
                name: "Juventus FC",
                shortName: "Juventus",
                tla: "JUV",
                crest: "https://crests.football-data.org/109.svg",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 0,
              lost: 5,
              points: 3,
              goalsFor: 9,
              goalsAgainst: 13,
              goalDifference: -4,
            },
            {
              position: 4,
              team: {
                id: 884,
                name: "Maccabi Haifa FC",
                shortName: "Maccabi Haifa",
                tla: "MHA",
                crest: "https://crests.football-data.org/884.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 0,
              lost: 5,
              points: 3,
              goalsFor: 7,
              goalsAgainst: 21,
              goalDifference: -14,
            },
          ],
        },
      ],
    };
  }

  static CompetitionScorers(): ICompetitionScorers {
    return {
      count: 10,
      filters: {
        season: "2022",
        limit: 10,
      },
      competition: {
        id: 2017,
        name: "Primeira Liga",
        code: "PPL",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PPL.png",
      },
      season: {
        id: 1518,
        startDate: "2022-08-07",
        endDate: "2023-05-28",
        currentMatchday: 14,
        winner: null,
      },
      scorers: [
        {
          player: {
            id: 101431,
            name: "Gonçalo Ramos",
            firstName: "",
            lastName: "Gonçalo Ramos",
            dateOfBirth: "2001-06-20",
            nationality: "Portugal",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 1903,
            name: "Sport Lisboa e Benfica",
            shortName: "SL Benfica",
            tla: "BEN",
            crest: "https://crests.football-data.org/1903.png",
            address: "null null null",
            website: "https://www.slbenfica.pt",
            founded: 2020,
            clubColors: null,
            venue: "Estádio do Sport Lisboa e Benfica",
            lastUpdated: "2022-02-19T09:13:16Z",
          },
          goals: 9,
          assists: null,
          penalties: null,
        },
        {
          player: {
            id: 102579,
            name: "Fran Navarro",
            firstName: "",
            lastName: "Fran Navarro",
            dateOfBirth: "1998-02-03",
            nationality: "Spain",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 5533,
            name: "Gil Vicente FC",
            shortName: "Gil Vicente",
            tla: "GIL",
            crest: "https://crests.football-data.org/5533.png",
            address:
              "Rua D. Diogo Pinheiro n.º 25, Apartado 197 Barcelos 4750-282",
            website: "http://www.gilvicentefc.pt",
            founded: 1924,
            clubColors: "Red / Blue",
            venue: "Estádio Cidade de Barcelos",
            lastUpdated: "2022-02-19T08:57:44Z",
          },
          goals: 8,
          assists: null,
          penalties: 2,
        },
        {
          player: {
            id: 16748,
            name: "Rafa Silva",
            firstName: "",
            lastName: "Rafa Silva",
            dateOfBirth: "1993-05-17",
            nationality: "Portugal",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-07-26T17:39:24Z",
          },
          team: {
            id: 1903,
            name: "Sport Lisboa e Benfica",
            shortName: "SL Benfica",
            tla: "BEN",
            crest: "https://crests.football-data.org/1903.png",
            address: "null null null",
            website: "https://www.slbenfica.pt",
            founded: 2020,
            clubColors: null,
            venue: "Estádio do Sport Lisboa e Benfica",
            lastUpdated: "2022-02-19T09:13:16Z",
          },
          goals: 6,
          assists: null,
          penalties: null,
        },
        {
          player: {
            id: 3820,
            name: "Mehdi Taremi",
            firstName: "Mehdi",
            lastName: "Taremi",
            dateOfBirth: "1992-07-18",
            nationality: "Iran",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 503,
            name: "FC Porto",
            shortName: "Porto",
            tla: "FCP",
            crest: "https://crests.football-data.org/503.png",
            address:
              "Estádio do Dragão, Entrada Poente - Piso 3 Porto 4350-451",
            website: "http://www.fcporto.pt",
            founded: 1893,
            clubColors: "Blue / White",
            venue: "Estádio Do Dragão",
            lastUpdated: "2022-02-10T19:26:43Z",
          },
          goals: 6,
          assists: null,
          penalties: 1,
        },
        {
          player: {
            id: 131260,
            name: "Evanilson",
            firstName: "",
            lastName: "Evanilson",
            dateOfBirth: "1999-10-06",
            nationality: "Brazil",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-07-26T17:39:24Z",
          },
          team: {
            id: 503,
            name: "FC Porto",
            shortName: "Porto",
            tla: "FCP",
            crest: "https://crests.football-data.org/503.png",
            address:
              "Estádio do Dragão, Entrada Poente - Piso 3 Porto 4350-451",
            website: "http://www.fcporto.pt",
            founded: 1893,
            clubColors: "Blue / White",
            venue: "Estádio Do Dragão",
            lastUpdated: "2022-02-10T19:26:43Z",
          },
          goals: 6,
          assists: null,
          penalties: null,
        },
        {
          player: {
            id: 92050,
            name: "Pedro Gonçalves",
            firstName: "",
            lastName: "Pedro Gonçalves",
            dateOfBirth: "1998-06-28",
            nationality: "Portugal",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 498,
            name: "Sporting Clube de Portugal",
            shortName: "Sporting CP",
            tla: "SPO",
            crest: "https://crests.football-data.org/498.png",
            address:
              "Edifício Visconde de Alvalade, Apartado 42099 Lisboa 1601-801",
            website: "http://www.sporting.pt",
            founded: 1906,
            clubColors: "Green / White",
            venue: "Estádio José Alvalade",
            lastUpdated: "2022-07-26T17:38:53Z",
          },
          goals: 6,
          assists: null,
          penalties: 2,
        },
        {
          player: {
            id: 52964,
            name: "Abdul-Aziz Yakubu",
            firstName: "Abdul-Aziz",
            lastName: null,
            dateOfBirth: "1998-11-10",
            nationality: "Ghana",
            position: "Midfield",
            shirtNumber: null,
            lastUpdated: "2022-07-26T17:40:46Z",
          },
          team: {
            id: 496,
            name: "Rio Ave FC",
            shortName: "Rio Ave",
            tla: "RIO",
            crest: "https://crests.football-data.org/496.png",
            address:
              "Praça da República, n.º35, Apartado 42 Vila do Conde 4481-909",
            website: "http://www.rioave-fc.pt",
            founded: 1939,
            clubColors: "Green / White",
            venue: "Estádio do Rio Ave Futebol Clube",
            lastUpdated: "2022-07-26T17:38:50Z",
          },
          goals: 6,
          assists: null,
          penalties: 1,
        },
        {
          player: {
            id: 3253,
            name: "João Mário",
            firstName: "",
            lastName: "João Mário",
            dateOfBirth: "1993-01-19",
            nationality: "Portugal",
            position: "Midfield",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 1903,
            name: "Sport Lisboa e Benfica",
            shortName: "SL Benfica",
            tla: "BEN",
            crest: "https://crests.football-data.org/1903.png",
            address: "null null null",
            website: "https://www.slbenfica.pt",
            founded: 2020,
            clubColors: null,
            venue: "Estádio do Sport Lisboa e Benfica",
            lastUpdated: "2022-02-19T09:13:16Z",
          },
          goals: 6,
          assists: null,
          penalties: 4,
        },
        {
          player: {
            id: 74554,
            name: "Simon Banza",
            firstName: "Simon",
            lastName: "Banza",
            dateOfBirth: "1996-08-13",
            nationality: "France",
            position: "Offence",
            shirtNumber: 23,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 5613,
            name: "Sporting Clube de Braga",
            shortName: "Braga",
            tla: "SCB",
            crest: "https://crests.football-data.org/5613.png",
            address: "Parque Norte, Monte Crasto, Apartado 12 Braga 4700-087",
            website: "http://www.scbraga.pt",
            founded: 1921,
            clubColors: "Red / White",
            venue: "Estádio Municipal de Braga",
            lastUpdated: "2022-02-19T08:44:56Z",
          },
          goals: 5,
          assists: null,
          penalties: null,
        },
        {
          player: {
            id: 32309,
            name: "Héctor Hernández",
            firstName: "Héctor",
            lastName: null,
            dateOfBirth: "1995-09-14",
            nationality: "Spain",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-07-26T17:40:46Z",
          },
          team: {
            id: 1103,
            name: "GD Chaves",
            shortName: "Chaves",
            tla: "CHA",
            crest:
              "https://upload.wikimedia.org/wikipedia/en/0/05/G_D_Chaves.png",
            address: "Av. do Estádio Municipal Apartado 225 Chaves 5400",
            website: "http://www.gdchaves.pt",
            founded: 1949,
            clubColors: "Red / Blue",
            venue: "Estádio Municipal Eng. Manuel Branco Teixeira",
            lastUpdated: "2020-11-19T02:16:09Z",
          },
          goals: 5,
          assists: null,
          penalties: null,
        },
      ],
    };
  }

  static Team(): ITeam {
    return {
      area: {
        id: 2072,
        name: "England",
        code: "ENG",
        flag: "https://crests.football-data.org/770.svg",
      },
      id: 57,
      name: "Arsenal FC",
      shortName: "Arsenal",
      tla: "ARS",
      crest: "https://crests.football-data.org/57.png",
      address: "75 Drayton Park London N5 1BU",
      website: "http://www.arsenal.com",
      founded: 1886,
      clubColors: "Red / White",
      venue: "Emirates Stadium",
      runningCompetitions: [
        {
          id: 2021,
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
        },
        {
          id: 2139,
          name: "Football League Cup",
          code: "FLC",
          type: "CUP",
          emblem: "https://crests.football-data.org/FLC.png",
        },
        {
          id: 2146,
          name: "UEFA Europa League",
          code: "EL",
          type: "CUP",
          emblem: "https://crests.football-data.org/EL.png",
        },
      ],
      coach: {
        id: 11619,
        firstName: "Mikel",
        lastName: null,
        name: "Arteta",
        dateOfBirth: "1982-03-26",
        nationality: "Spain",
        contract: {
          start: null,
          until: null,
        },
      },
      squad: [
        {
          id: 5530,
          name: "Aaron Ramsdale",
          position: "Goalkeeper",
          dateOfBirth: "1998-05-14",
          nationality: "England",
        },
        {
          id: 76936,
          name: "Matt Turner",
          position: "Goalkeeper",
          dateOfBirth: "1994-06-24",
          nationality: "United States",
        },
        {
          id: 3244,
          name: "Cédric",
          position: "Defence",
          dateOfBirth: "1991-08-31",
          nationality: "Portugal",
        },
        {
          id: 6154,
          name: "Ben White",
          position: "Defence",
          dateOfBirth: "1997-10-08",
          nationality: "England",
        },
        {
          id: 7784,
          name: "Rob Holding",
          position: "Defence",
          dateOfBirth: "1995-09-20",
          nationality: "England",
        },
        {
          id: 7889,
          name: "Oleksandr Zinchenko",
          position: "Defence",
          dateOfBirth: "1996-12-15",
          nationality: "Ukraine",
        },
        {
          id: 9034,
          name: "Takehiro Tomiyasu",
          position: "Defence",
          dateOfBirth: "1998-11-05",
          nationality: "Japan",
        },
        {
          id: 15615,
          name: "Kieran Tierney",
          position: "Defence",
          dateOfBirth: "1997-06-05",
          nationality: "Scotland",
        },
        {
          id: 23128,
          name: "Gabriel",
          position: "Defence",
          dateOfBirth: "1997-12-19",
          nationality: "Brazil",
        },
        {
          id: 80171,
          name: "William Saliba",
          position: "Defence",
          dateOfBirth: "2001-03-24",
          nationality: "France",
        },
        {
          id: 110,
          name: "Thomas Partey",
          position: "Midfield",
          dateOfBirth: "1993-06-13",
          nationality: "Ghana",
        },
        {
          id: 3477,
          name: "Granit Xhaka",
          position: "Midfield",
          dateOfBirth: "1992-09-27",
          nationality: "Switzerland",
        },
        {
          id: 3755,
          name: "Mohamed El Neny",
          position: "Midfield",
          dateOfBirth: "1992-07-11",
          nationality: "Egypt",
        },
        {
          id: 7427,
          name: "Martin Ødegaard",
          position: "Midfield",
          dateOfBirth: "1998-12-17",
          nationality: "Norway",
        },
        {
          id: 8862,
          name: "Albert Sambi Lokonga",
          position: "Midfield",
          dateOfBirth: "1999-10-22",
          nationality: "Belgium",
        },
        {
          id: 85570,
          name: "Emile Smith Rowe",
          position: "Midfield",
          dateOfBirth: "2000-07-28",
          nationality: "England",
        },
        {
          id: 112948,
          name: "Fabio Vieira",
          position: "Midfield",
          dateOfBirth: "2000-05-30",
          nationality: "Portugal",
        },
        {
          id: 169277,
          name: "Marquinhos",
          position: "Midfield",
          dateOfBirth: "2003-04-07",
          nationality: "Brazil",
        },
        {
          id: 3236,
          name: "Gabriel Jesus",
          position: "Offence",
          dateOfBirth: "1997-04-03",
          nationality: "Brazil",
        },
        {
          id: 7799,
          name: "Reiss Nelson",
          position: "Offence",
          dateOfBirth: "1999-12-10",
          nationality: "England",
        },
        {
          id: 7800,
          name: "Eddie Nketiah",
          position: "Offence",
          dateOfBirth: "1999-05-30",
          nationality: "England",
        },
        {
          id: 61450,
          name: "Martinelli",
          position: "Offence",
          dateOfBirth: "2001-06-18",
          nationality: "Brazil",
        },
        {
          id: 99813,
          name: "Bukayo Saka",
          position: "Offence",
          dateOfBirth: "2001-09-05",
          nationality: "England",
        },
      ],
      staff: [],
      lastUpdated: "2022-02-10T19:48:56Z",
    };
  }
}
