import { ICompetitionMatches } from "types/competiiton_matches";
import { IRootCompetition } from "types/competition";
import { ICompetitionScorers } from "types/competition_scorers";
import { ICompetitionStandings } from "types/competition_standings";
import { ICompetitionTeam } from "types/competition_teams";
import { IHead2Head } from "types/head2Head";
import { IInfoMatch } from "types/infoMatch";
import { ITeam } from "types/team";

export class DataFake {
  /**
   *
   *
   * @static
   * @return {*}  {IRootCompetition}
   * @memberof DataFake
   */
  static CompetitionsAreas(): IRootCompetition {
    return {
      count: 13,
      filters: {
        client: "Minh Nguyen",
      },
      competitions: [
        {
          id: 2013,
          area: {
            id: 2032,
            name: "Brazil",
            code: "BRA",
            flag: "https://crests.football-data.org/764.svg",
          },
          name: "Campeonato Brasileiro Série A",
          code: "BSA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/764.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1377,
            startDate: "2022-04-10",
            endDate: "2022-11-13",
            currentMatchday: 38,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2021-07-20T18:42:17Z",
        },
        {
          id: 2016,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Championship",
          code: "ELC",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ELC.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1502,
            startDate: "2022-07-29",
            endDate: "2023-05-06",
            currentMatchday: 23,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2022-03-20T09:31:30Z",
        },
        {
          id: 2021,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1490,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 17,
            winner: null,
          },
          numberOfAvailableSeasons: 124,
          lastUpdated: "2022-03-20T08:58:54Z",
        },
        {
          id: 2001,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "UEFA Champions League",
          code: "CL",
          type: "CUP",
          emblem: "https://crests.football-data.org/CL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1491,
            startDate: "2022-06-21",
            endDate: "2023-06-10",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 43,
          lastUpdated: "2022-03-20T09:20:44Z",
        },
        {
          id: 2018,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "European Championship",
          code: "EC",
          type: "CUP",
          emblem: "https://crests.football-data.org/EUR.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1537,
            startDate: "2024-06-14",
            endDate: "2024-07-14",
            currentMatchday: 1,
            winner: null,
          },
          numberOfAvailableSeasons: 17,
          lastUpdated: "2021-07-20T18:34:04Z",
        },
        {
          id: 2015,
          area: {
            id: 2081,
            name: "France",
            code: "FRA",
            flag: "https://crests.football-data.org/773.svg",
          },
          name: "Ligue 1",
          code: "FL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/FL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1497,
            startDate: "2022-08-07",
            endDate: "2023-06-03",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 79,
          lastUpdated: "2022-03-20T09:30:02Z",
        },
        {
          id: 2002,
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          name: "Bundesliga",
          code: "BL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/BL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1495,
            startDate: "2022-08-05",
            endDate: "2023-05-27",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 60,
          lastUpdated: "2022-03-20T08:52:53Z",
        },
        {
          id: 2019,
          area: {
            id: 2114,
            name: "Italy",
            code: "ITA",
            flag: "https://crests.football-data.org/784.svg",
          },
          name: "Serie A",
          code: "SA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/SA.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1505,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 91,
          lastUpdated: "2022-03-20T09:16:43Z",
        },
        {
          id: 2003,
          area: {
            id: 2163,
            name: "Netherlands",
            code: "NLD",
            flag: "https://crests.football-data.org/8601.svg",
          },
          name: "Eredivisie",
          code: "DED",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ED.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1494,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 67,
          lastUpdated: "2022-03-20T09:19:27Z",
        },
        {
          id: 2017,
          area: {
            id: 2187,
            name: "Portugal",
            code: "PRT",
            flag: "https://crests.football-data.org/765.svg",
          },
          name: "Primeira Liga",
          code: "PPL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PPL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1518,
            startDate: "2022-08-07",
            endDate: "2023-05-28",
            currentMatchday: 14,
            winner: null,
          },
          numberOfAvailableSeasons: 74,
          lastUpdated: "2022-03-20T09:34:09Z",
        },
        {
          id: 2152,
          area: {
            id: 2220,
            name: "South America",
            code: "SAM",
            flag: "https://crests.football-data.org/CLI.svg",
          },
          name: "Copa Libertadores",
          code: "CLI",
          type: "CUP",
          emblem: "https://native-stats.org/assets/flags/SAM.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 873,
            startDate: "2022-02-09",
            endDate: "2022-09-06",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 2,
          lastUpdated: "2022-10-31T15:20:09Z",
        },
        {
          id: 2014,
          area: {
            id: 2224,
            name: "Spain",
            code: "ESP",
            flag: "https://crests.football-data.org/760.svg",
          },
          name: "Primera Division",
          code: "PD",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PD.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1504,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 92,
          lastUpdated: "2022-03-20T09:20:08Z",
        },
        {
          id: 2000,
          area: {
            id: 2267,
            name: "World",
            code: "INT",
            flag: null,
          },
          name: "FIFA World Cup",
          code: "WC",
          type: "CUP",
          emblem: "https://crests.football-data.org/qatar.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1382,
            startDate: "2022-11-20",
            endDate: "2022-12-18",
            currentMatchday: 8,
            winner: null,
          },
          numberOfAvailableSeasons: 22,
          lastUpdated: "2022-05-09T19:45:29Z",
        },
      ],
    };
  }

  static CompetitionsStandings(): ICompetitionStandings {
    return {
      filters: {
        season: "2022",
      },
      area: {
        id: 2077,
        name: "Europe",
        code: "EUR",
        flag: "https://crests.football-data.org/EUR.svg",
      },
      competition: {
        id: 2001,
        name: "UEFA Champions League",
        code: "CL",
        type: "CUP",
        emblem: "https://crests.football-data.org/CL.png",
      },
      season: {
        id: 1491,
        startDate: "2022-06-21",
        endDate: "2023-06-10",
        currentMatchday: 6,
        winner: null,
      },
      standings: [
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_A",
          table: [
            {
              position: 1,
              team: {
                id: 113,
                name: "SSC Napoli",
                shortName: "Napoli",
                tla: "NAP",
                crest: "https://crests.football-data.org/113.svg",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 20,
              goalsAgainst: 6,
              goalDifference: 14,
            },
            {
              position: 2,
              team: {
                id: 64,
                name: "Liverpool FC",
                shortName: "Liverpool",
                tla: "LIV",
                crest: "https://crests.football-data.org/64.png",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 17,
              goalsAgainst: 6,
              goalDifference: 11,
            },
            {
              position: 3,
              team: {
                id: 678,
                name: "AFC Ajax",
                shortName: "Ajax",
                tla: "AJA",
                crest: "https://crests.football-data.org/678.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 0,
              lost: 4,
              points: 6,
              goalsFor: 11,
              goalsAgainst: 16,
              goalDifference: -5,
            },
            {
              position: 4,
              team: {
                id: 5376,
                name: "Rangers FC",
                shortName: "Rangers",
                tla: "RAN",
                crest: "https://crests.football-data.org/5376.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 0,
              lost: 6,
              points: 0,
              goalsFor: 2,
              goalsAgainst: 22,
              goalDifference: -20,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_B",
          table: [
            {
              position: 1,
              team: {
                id: 503,
                name: "FC Porto",
                shortName: "Porto",
                tla: "FCP",
                crest: "https://crests.football-data.org/503.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 0,
              lost: 2,
              points: 12,
              goalsFor: 12,
              goalsAgainst: 7,
              goalDifference: 5,
            },
            {
              position: 2,
              team: {
                id: 851,
                name: "Club Brugge KV",
                shortName: "Club Brugge",
                tla: "CLU",
                crest: "https://crests.football-data.org/851.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 2,
              lost: 1,
              points: 11,
              goalsFor: 7,
              goalsAgainst: 4,
              goalDifference: 3,
            },
            {
              position: 3,
              team: {
                id: 3,
                name: "Bayer 04 Leverkusen",
                shortName: "Leverkusen",
                tla: "B04",
                crest: "https://crests.football-data.org/3.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 4,
              goalsAgainst: 8,
              goalDifference: -4,
            },
            {
              position: 4,
              team: {
                id: 78,
                name: "Club Atlético de Madrid",
                shortName: "Atleti",
                tla: "ATL",
                crest: "https://crests.football-data.org/78.svg",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 5,
              goalsAgainst: 9,
              goalDifference: -4,
            },
          ],
        },
      ],
    };
  }

  static CompetitionScorers(): ICompetitionScorers {
    return {
      count: 10,
      filters: {
        season: "2022",
        limit: 10,
      },
      competition: {
        id: 2017,
        name: "Primeira Liga",
        code: "PPL",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PPL.png",
      },
      season: {
        id: 1518,
        startDate: "2022-08-07",
        endDate: "2023-05-28",
        currentMatchday: 14,
        winner: null,
      },
      scorers: [
        {
          player: {
            id: 101431,
            name: "Gonçalo Ramos",
            firstName: "",
            lastName: "Gonçalo Ramos",
            dateOfBirth: "2001-06-20",
            nationality: "Portugal",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 1903,
            name: "Sport Lisboa e Benfica",
            shortName: "SL Benfica",
            tla: "BEN",
            crest: "https://crests.football-data.org/1903.png",
            address: "null null null",
            website: "https://www.slbenfica.pt",
            founded: 2020,
            clubColors: null,
            venue: "Estádio do Sport Lisboa e Benfica",
            lastUpdated: "2022-02-19T09:13:16Z",
          },
          goals: 9,
          assists: null,
          penalties: null,
        },
      ],
    };
  }

  static Team(): ITeam {
    return {
      area: {
        id: 2072,
        name: "England",
        code: "ENG",
        flag: "https://crests.football-data.org/770.svg",
      },
      id: 57,
      name: "Arsenal FC",
      shortName: "Arsenal",
      tla: "ARS",
      crest: "https://crests.football-data.org/57.png",
      address: "75 Drayton Park London N5 1BU",
      website: "http://www.arsenal.com",
      founded: 1886,
      clubColors: "Red / White",
      venue: "Emirates Stadium",
      runningCompetitions: [
        {
          id: 2021,
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
        },
        {
          id: 2139,
          name: "Football League Cup",
          code: "FLC",
          type: "CUP",
          emblem: "https://crests.football-data.org/FLC.png",
        },
        {
          id: 2146,
          name: "UEFA Europa League",
          code: "EL",
          type: "CUP",
          emblem: "https://crests.football-data.org/EL.png",
        },
      ],
      coach: {
        id: 11619,
        firstName: "Mikel",
        lastName: null,
        name: "Arteta",
        dateOfBirth: "1982-03-26",
        nationality: "Spain",
        contract: {
          start: null,
          until: null,
        },
      },
      squad: [
        {
          id: 5530,
          name: "Aaron Ramsdale",
          position: "Goalkeeper",
          dateOfBirth: "1998-05-14",
          nationality: "England",
        },
      ],
      staff: [],
      lastUpdated: "2022-02-10T19:48:56Z",
    };
  }
  static CompetitionsTeams(): ICompetitionTeam {
    return {
      count: 20,
      filters: {
        season: "2022",
      },
      competition: {
        id: 2021,
        name: "Premier League",
        code: "PL",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PL.png",
      },
      season: {
        id: 1490,
        startDate: "2022-08-05",
        endDate: "2023-05-28",
        currentMatchday: 17,
        winner: null,
      },
      teams: [
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 57,
          name: "Arsenal FC",
          shortName: "Arsenal",
          tla: "ARS",
          crest: "https://crests.football-data.org/57.png",
          address: "75 Drayton Park London N5 1BU",
          website: "http://www.arsenal.com",
          founded: 1886,
          clubColors: "Red / White",
          venue: "Emirates Stadium",
          runningCompetitions: [
            {
              id: 2021,
              name: "Premier League",
              code: "PL",
              type: "LEAGUE",
              emblem: "https://crests.football-data.org/PL.png",
            },
            {
              id: 2139,
              name: "Football League Cup",
              code: "FLC",
              type: "CUP",
              emblem: "https://crests.football-data.org/FLC.png",
            },
            {
              id: 2146,
              name: "UEFA Europa League",
              code: "EL",
              type: "CUP",
              emblem: "https://crests.football-data.org/EL.png",
            },
          ],
          coach: {
            id: 11619,
            firstName: "Mikel",
            lastName: null,
            name: "Arteta",
            dateOfBirth: "1982-03-26",
            nationality: "Spain",
            contract: {
              start: null,
              until: null,
            },
          },
          squad: [
            {
              id: 5530,
              name: "Aaron Ramsdale",
              position: "Goalkeeper",
              dateOfBirth: "1998-05-14",
              nationality: "England",
            },
            {
              id: 76936,
              name: "Matt Turner",
              position: "Goalkeeper",
              dateOfBirth: "1994-06-24",
              nationality: "United States",
            },
            {
              id: 3244,
              name: "Cédric",
              position: "Defence",
              dateOfBirth: "1991-08-31",
              nationality: "Portugal",
            },
            {
              id: 6154,
              name: "Ben White",
              position: "Defence",
              dateOfBirth: "1997-10-08",
              nationality: "England",
            },
            {
              id: 7784,
              name: "Rob Holding",
              position: "Defence",
              dateOfBirth: "1995-09-20",
              nationality: "England",
            },
            {
              id: 7889,
              name: "Oleksandr Zinchenko",
              position: "Defence",
              dateOfBirth: "1996-12-15",
              nationality: "Ukraine",
            },
            {
              id: 9034,
              name: "Takehiro Tomiyasu",
              position: "Defence",
              dateOfBirth: "1998-11-05",
              nationality: "Japan",
            },
            {
              id: 15615,
              name: "Kieran Tierney",
              position: "Defence",
              dateOfBirth: "1997-06-05",
              nationality: "Scotland",
            },
            {
              id: 23128,
              name: "Gabriel",
              position: "Defence",
              dateOfBirth: "1997-12-19",
              nationality: "Brazil",
            },
            {
              id: 80171,
              name: "William Saliba",
              position: "Defence",
              dateOfBirth: "2001-03-24",
              nationality: "France",
            },
            {
              id: 110,
              name: "Thomas Partey",
              position: "Midfield",
              dateOfBirth: "1993-06-13",
              nationality: "Ghana",
            },
            {
              id: 3477,
              name: "Granit Xhaka",
              position: "Midfield",
              dateOfBirth: "1992-09-27",
              nationality: "Switzerland",
            },
            {
              id: 3755,
              name: "Mohamed El Neny",
              position: "Midfield",
              dateOfBirth: "1992-07-11",
              nationality: "Egypt",
            },
            {
              id: 7427,
              name: "Martin Ødegaard",
              position: "Midfield",
              dateOfBirth: "1998-12-17",
              nationality: "Norway",
            },
            {
              id: 8862,
              name: "Albert Sambi Lokonga",
              position: "Midfield",
              dateOfBirth: "1999-10-22",
              nationality: "Belgium",
            },
            {
              id: 85570,
              name: "Emile Smith Rowe",
              position: "Midfield",
              dateOfBirth: "2000-07-28",
              nationality: "England",
            },
            {
              id: 112948,
              name: "Fabio Vieira",
              position: "Midfield",
              dateOfBirth: "2000-05-30",
              nationality: "Portugal",
            },
            {
              id: 169277,
              name: "Marquinhos",
              position: "Midfield",
              dateOfBirth: "2003-04-07",
              nationality: "Brazil",
            },
            {
              id: 3236,
              name: "Gabriel Jesus",
              position: "Offence",
              dateOfBirth: "1997-04-03",
              nationality: "Brazil",
            },
            {
              id: 7799,
              name: "Reiss Nelson",
              position: "Offence",
              dateOfBirth: "1999-12-10",
              nationality: "England",
            },
            {
              id: 7800,
              name: "Eddie Nketiah",
              position: "Offence",
              dateOfBirth: "1999-05-30",
              nationality: "England",
            },
            {
              id: 61450,
              name: "Martinelli",
              position: "Offence",
              dateOfBirth: "2001-06-18",
              nationality: "Brazil",
            },
            {
              id: 99813,
              name: "Bukayo Saka",
              position: "Offence",
              dateOfBirth: "2001-09-05",
              nationality: "England",
            },
          ],
          staff: [],
          lastUpdated: "2022-02-10T19:48:56Z",
        },
      ],
    };
  }

  static CompetitionsMatches(): ICompetitionMatches {
    return {
      filters: {
        season: "2022",
      },
      resultSet: {
        count: 6,
        first: "2022-12-28",
        last: "2022-12-28",
        played: 0,
      },
      competition: {
        id: 2015,
        name: "Ligue 1",
        code: "FL1",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/FL1.png",
      },
      matches: [
        {
          area: {
            id: 2081,
            name: "France",
            code: "FRA",
            flag: "https://crests.football-data.org/773.svg",
          },
          competition: {
            id: 2015,
            name: "Ligue 1",
            code: "FL1",
            type: "LEAGUE",
            emblem: "https://crests.football-data.org/FL1.png",
          },
          season: {
            id: 1497,
            startDate: "2022-08-07",
            endDate: "2023-06-03",
            currentMatchday: 16,
            winner: null,
          },
          id: 417109,
          utcDate: "2022-12-28T14:00:00Z",
          status: "TIMED",
          matchday: 16,
          stage: "REGULAR_SEASON",
          group: null,
          lastUpdated: "2022-11-19T16:20:09Z",
          homeTeam: {
            id: 531,
            name: "ES Troyes AC",
            shortName: "Troyes",
            tla: "ETR",
            crest: "https://crests.football-data.org/531.svg",
          },
          awayTeam: {
            id: 543,
            name: "FC Nantes",
            shortName: "Nantes",
            tla: "NAN",
            crest: "https://crests.football-data.org/543.svg",
          },
          score: {
            winner: null,
            duration: "REGULAR",
            fullTime: {
              home: null,
              away: null,
            },
            halfTime: {
              home: null,
              away: null,
            },
          },
          odds: {
            homeWin: 2.09,
            draw: 3.66,
            awayWin: 3.76,
          },
          referees: [],
        },
      ],
    };
  }

  static InfoMatch(): IInfoMatch {
    return {
      area: {
        id: 2072,
        name: "England",
        code: "ENG",
        flag: "https://crests.football-data.org/770.svg",
      },
      competition: {
        id: 2016,
        name: "Championship",
        code: "ELC",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/ELC.png",
      },
      season: {
        id: 1502,
        startDate: "2022-07-29",
        endDate: "2023-05-06",
        currentMatchday: 25,
        winner: null,
        stages: ["REGULAR_SEASON"],
      },
      id: 422666,
      utcDate: "2022-07-30T14:00:00Z",
      status: "FINISHED",
      minute: 90,
      injuryTime: 7,
      attendance: 10454,
      venue: "New York Stadium",
      matchday: 1,
      stage: "REGULAR_SEASON",
      group: null,
      lastUpdated: "2022-12-29T08:20:11Z",
      homeTeam: {
        id: 385,
        name: "Rotherham United FC",
        shortName: "Rotherham Utd",
        tla: "ROT",
        crest: "https://crests.football-data.org/385.png",
        coach: {
          id: 14603,
          name: "Paul Warne",
          nationality: "England",
        },
        leagueRank: 16,
        formation: "3-1-4-2",
        lineup: [
          {
            id: 149732,
            name: "Viktor Johansson",
            position: "Goalkeeper",
            shirtNumber: 1,
          },
          {
            id: 4014,
            name: "Grant Hall",
            position: "Centre-Back",
            shirtNumber: 20,
          },
          {
            id: 4368,
            name: "Shane Ferguson",
            position: "Left Midfield",
            shirtNumber: 17,
          },
          {
            id: 4111,
            name: "Wes Harding",
            position: "Right-Back",
            shirtNumber: 2,
          },
          {
            id: 114000,
            name: "Cameron Humphreys",
            position: "Centre-Back",
            shirtNumber: 24,
          },
          {
            id: 34549,
            name: "Jamie Lindsay",
            position: "Central Midfield",
            shirtNumber: 16,
          },
          {
            id: 6447,
            name: "Richard Wood",
            position: "Centre-Back",
            shirtNumber: 6,
          },
          {
            id: 4440,
            name: "Chiedozie Ogbene",
            position: "Right Winger",
            shirtNumber: 11,
          },
          {
            id: 6467,
            name: "Ben Wiles",
            position: "Central Midfield",
            shirtNumber: 8,
          },
          {
            id: 58086,
            name: "Daniel Barlaser",
            position: "Central Midfield",
            shirtNumber: 4,
          },
          {
            id: 4034,
            name: "Conor Washington",
            position: "Centre-Forward",
            shirtNumber: 14,
          },
        ],
        bench: [
          {
            id: 5830,
            name: "Josh Vickers",
            position: "Goalkeeper",
            shirtNumber: 31,
          },
          {
            id: 60866,
            name: "Hakeem Odoffin",
            position: "Defensive Midfield",
            shirtNumber: 22,
          },
          {
            id: 76779,
            name: "Peter Kioso",
            position: null,
            shirtNumber: 0,
          },
          {
            id: 4113,
            name: "Cohen Bramall",
            position: "Left-Back",
            shirtNumber: 15,
          },
          {
            id: 35280,
            name: "Jamie McCart",
            position: "Centre-Back",
            shirtNumber: 0,
          },
          {
            id: 76779,
            name: "Peter Kioso",
            position: null,
            shirtNumber: 30,
          },
          {
            id: 4113,
            name: "Cohen Bramall",
            position: "Left-Back",
            shirtNumber: 3,
          },
          {
            id: 35280,
            name: "Jamie McCart",
            position: "Centre-Back",
            shirtNumber: 5,
          },
          {
            id: 136728,
            name: "Scott High",
            position: null,
            shirtNumber: 0,
          },
          {
            id: 136728,
            name: "Scott High",
            position: null,
            shirtNumber: 7,
          },
          {
            id: 58189,
            name: "Georgie Kelly",
            position: "Centre-Forward",
            shirtNumber: 12,
          },
        ],
        statistics: {
          msg: "Subscribe to Stats-Package in User-Panel to retrieve team statistics like ball possession, fouls, no of shots and more...",
        },
      },
      awayTeam: {
        id: 72,
        name: "Swansea City AFC",
        shortName: "Swansea",
        tla: "SWA",
        crest: "https://crests.football-data.org/72.png",
        coach: {
          id: 11321,
          name: "Russell Martin",
          nationality: "Scotland",
        },
        leagueRank: 20,
        formation: "3-4-3",
        lineup: [
          {
            id: 4833,
            name: "Andy Fisher",
            position: "Goalkeeper",
            shirtNumber: 1,
          },
          {
            id: 76745,
            name: "Nathan Wood-Gordon",
            position: "Centre-Back",
            shirtNumber: 23,
          },
          {
            id: 128952,
            name: "Matthew Sorinola",
            position: "Left-Back",
            shirtNumber: 29,
          },
          {
            id: 130044,
            name: "Joel Latibeaudiere",
            position: "Centre-Back",
            shirtNumber: 22,
          },
          {
            id: 6276,
            name: "Harry Darling",
            position: "Centre-Back",
            shirtNumber: 6,
          },
          {
            id: 7969,
            name: "Kyle Naughton",
            position: "Right-Back",
            shirtNumber: 26,
          },
          {
            id: 6358,
            name: "Matt Grimes",
            position: "Central Midfield",
            shirtNumber: 8,
          },
          {
            id: 4896,
            name: "Jay Fulton",
            position: "Central Midfield",
            shirtNumber: 4,
          },
          {
            id: 67978,
            name: "Joël Piroe",
            position: "Centre-Forward",
            shirtNumber: 17,
          },
          {
            id: 4408,
            name: "Jamie Paterson",
            position: "Offence",
            shirtNumber: 12,
          },
          {
            id: 8102,
            name: "Michael Obafemi",
            position: "Centre-Forward",
            shirtNumber: 9,
          },
        ],
        bench: [
          {
            id: 81055,
            name: "Steven Benda",
            position: "Goalkeeper",
            shirtNumber: 13,
          },
          {
            id: 4024,
            name: "Ryan Manning",
            position: "Left-Back",
            shirtNumber: 3,
          },
          {
            id: 59089,
            name: "Benjamin Cabango",
            position: "Centre-Back",
            shirtNumber: 5,
          },
          {
            id: 82151,
            name: "Liam Cullen",
            position: "Centre-Forward",
            shirtNumber: 20,
          },
          {
            id: 15717,
            name: "Jules Ntcham",
            position: "Central Midfield",
            shirtNumber: 10,
          },
          {
            id: 154747,
            name: "Oliver Cooper",
            position: "Attacking Midfield",
            shirtNumber: 31,
          },
          {
            id: 178001,
            name: "Cameron Congreve",
            position: null,
            shirtNumber: 45,
          },
        ],
        statistics: {
          msg: "Subscribe to Stats-Package in User-Panel to retrieve team statistics like ball possession, fouls, no of shots and more...",
        },
      },
      score: {
        winner: "DRAW",
        duration: "REGULAR",
        fullTime: {
          home: 1,
          away: 1,
        },
        halfTime: {
          home: 1,
          away: 1,
        },
      },
      goals: [
        {
          minute: 16,
          injuryTime: null,
          type: "REGULAR",
          team: {
            id: 385,
            name: "Rotherham United FC",
          },
          scorer: {
            id: 4440,
            name: "Chiedozie Ogbene",
          },
          assist: null,
          score: {
            home: 1,
            away: 0,
          },
        },
        {
          minute: 38,
          injuryTime: null,
          type: "REGULAR",
          team: {
            id: 72,
            name: "Swansea City AFC",
          },
          scorer: {
            id: 6276,
            name: "Harry Darling",
          },
          assist: null,
          score: {
            home: 1,
            away: 1,
          },
        },
      ],
      penalties: [],
      bookings: [
        {
          minute: 55,
          team: {
            id: 72,
            name: "Swansea City AFC",
          },
          player: {
            id: 128952,
            name: "Matthew Sorinola",
          },
          card: "YELLOW",
        },
        {
          minute: 80,
          team: {
            id: 72,
            name: "Swansea City AFC",
          },
          player: {
            id: 67978,
            name: "Joël Piroe",
          },
          card: "YELLOW",
        },
        {
          minute: 90,
          team: {
            id: 385,
            name: "Rotherham United FC",
          },
          player: {
            id: 4113,
            name: "Cohen Bramall",
          },
          card: "YELLOW",
        },
      ],
      substitutions: [
        {
          minute: 66,
          team: {
            id: 385,
            name: "Rotherham United FC",
          },
          playerOut: {
            id: 4014,
            name: "Grant Hall",
          },
          playerIn: {
            id: 76779,
            name: "Peter Kioso",
          },
        },
        {
          minute: 66,
          team: {
            id: 385,
            name: "Rotherham United FC",
          },
          playerOut: {
            id: 4034,
            name: "Conor Washington",
          },
          playerIn: {
            id: 58189,
            name: "Georgie Kelly",
          },
        },
        {
          minute: 66,
          team: {
            id: 385,
            name: "Rotherham United FC",
          },
          playerOut: {
            id: 4368,
            name: "Shane Ferguson",
          },
          playerIn: {
            id: 4113,
            name: "Cohen Bramall",
          },
        },
        {
          minute: 71,
          team: {
            id: 72,
            name: "Swansea City AFC",
          },
          playerOut: {
            id: 4408,
            name: "Jamie Paterson",
          },
          playerIn: {
            id: 15717,
            name: "Jules Ntcham",
          },
        },
        {
          minute: 72,
          team: {
            id: 72,
            name: "Swansea City AFC",
          },
          playerOut: {
            id: 128952,
            name: "Matthew Sorinola",
          },
          playerIn: {
            id: 4024,
            name: "Ryan Manning",
          },
        },
      ],
      odds: {
        msg: "Activate Odds-Package in User-Panel to retrieve odds.",
      },
      referees: [],
    };
  }

  static Head2Head(): IHead2Head {
    return {
      filters: {
        limit: 15,
        permission: "FREE_PLUS_THREE_QLY",
      },
      resultSet: {
        count: 6,
        competitions: "PL",
        first: "2020-03-08",
        last: "2022-10-02",
      },
      aggregates: {
        numberOfMatches: 15,
        totalGoals: 44,
        homeTeam: {
          id: 65,
          name: "Manchester City FC",
          wins: 8,
          draws: 2,
          losses: 5,
        },
        awayTeam: {
          id: 66,
          name: "Manchester United FC",
          wins: 5,
          draws: 2,
          losses: 8,
        },
      },
      matches: [
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          competition: {
            id: 2021,
            name: "Premier League",
            code: "PL",
            type: "LEAGUE",
            emblem: "https://crests.football-data.org/PL.png",
          },
          season: {
            id: 1490,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 17,
            winner: null,
            stages: ["REGULAR_SEASON"],
          },
          id: 416297,
          utcDate: "2022-10-02T13:00:00Z",
          status: "FINISHED",
          minute: 90,
          injuryTime: 3,
          attendance: 53475,
          venue: "Etihad Stadium",
          matchday: 9,
          stage: "REGULAR_SEASON",
          group: null,
          lastUpdated: "2022-12-29T00:20:30Z",
          homeTeam: {
            id: 65,
            name: "Manchester City FC",
            shortName: "Man City",
            tla: "MCI",
            crest: "https://crests.football-data.org/65.png",
            coach: {
              id: 11603,
              name: "Pep Guardiola",
              nationality: "Spain",
            },
            leagueRank: 2,
            formation: "4-3-3",
            lineup: [],
            bench: [],
          },
          awayTeam: {
            id: 66,
            name: "Manchester United FC",
            shortName: "Man United",
            tla: "MUN",
            crest: "https://crests.football-data.org/66.png",
            coach: {
              id: 9584,
              name: "Erik ten Hag",
              nationality: "Netherlands",
            },
            leagueRank: 6,
            formation: "4-2-3-1",
            lineup: [],
            bench: [],
          },
          score: {
            winner: "HOME_TEAM",
            duration: "REGULAR",
            fullTime: {
              home: 6,
              away: 3,
            },
            halfTime: {
              home: 4,
              away: 0,
            },
          },
          goals: [],
          penalties: [],
          bookings: [],
          substitutions: [],
          odds: {
            msg: "Activate Odds-Package in User-Panel to retrieve odds.",
          },
          referees: [
            {
              id: 11605,
              name: "Michael Oliver",
              type: "REFEREE",
              nationality: "England",
            },
          ],
        },
      ],
    };
  }
}
