import { ICompetitionMatches } from "../@types/competiiton_matches";
import { IRootCompetition } from "../@types/competition";
import { ICompetitionScorers } from "../@types/competition_scorers";
import { ICompetitionStandings } from "../@types/competition_standings";
import { ICompetitionTeam } from "../@types/competition_teams";
import { ITeam } from "../@types/team";

export class DataFake {
  /**
   *
   *
   * @static
   * @return {*}  {IRootCompetition}
   * @memberof DataFake
   */
  static CompetitionsAreas(): IRootCompetition {
    return {
      count: 13,
      filters: {
        client: "Minh Nguyen",
      },
      competitions: [
        {
          id: 2013,
          area: {
            id: 2032,
            name: "Brazil",
            code: "BRA",
            flag: "https://crests.football-data.org/764.svg",
          },
          name: "Campeonato Brasileiro Série A",
          code: "BSA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/764.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1377,
            startDate: "2022-04-10",
            endDate: "2022-11-13",
            currentMatchday: 38,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2021-07-20T18:42:17Z",
        },
        {
          id: 2016,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Championship",
          code: "ELC",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ELC.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1502,
            startDate: "2022-07-29",
            endDate: "2023-05-06",
            currentMatchday: 23,
            winner: null,
          },
          numberOfAvailableSeasons: 6,
          lastUpdated: "2022-03-20T09:31:30Z",
        },
        {
          id: 2021,
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1490,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 17,
            winner: null,
          },
          numberOfAvailableSeasons: 124,
          lastUpdated: "2022-03-20T08:58:54Z",
        },
        {
          id: 2001,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "UEFA Champions League",
          code: "CL",
          type: "CUP",
          emblem: "https://crests.football-data.org/CL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1491,
            startDate: "2022-06-21",
            endDate: "2023-06-10",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 43,
          lastUpdated: "2022-03-20T09:20:44Z",
        },
        {
          id: 2018,
          area: {
            id: 2077,
            name: "Europe",
            code: "EUR",
            flag: "https://crests.football-data.org/EUR.svg",
          },
          name: "European Championship",
          code: "EC",
          type: "CUP",
          emblem: "https://crests.football-data.org/EUR.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1537,
            startDate: "2024-06-14",
            endDate: "2024-07-14",
            currentMatchday: 1,
            winner: null,
          },
          numberOfAvailableSeasons: 17,
          lastUpdated: "2021-07-20T18:34:04Z",
        },
        {
          id: 2015,
          area: {
            id: 2081,
            name: "France",
            code: "FRA",
            flag: "https://crests.football-data.org/773.svg",
          },
          name: "Ligue 1",
          code: "FL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/FL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1497,
            startDate: "2022-08-07",
            endDate: "2023-06-03",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 79,
          lastUpdated: "2022-03-20T09:30:02Z",
        },
        {
          id: 2002,
          area: {
            id: 2088,
            name: "Germany",
            code: "DEU",
            flag: "https://crests.football-data.org/759.svg",
          },
          name: "Bundesliga",
          code: "BL1",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/BL1.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1495,
            startDate: "2022-08-05",
            endDate: "2023-05-27",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 60,
          lastUpdated: "2022-03-20T08:52:53Z",
        },
        {
          id: 2019,
          area: {
            id: 2114,
            name: "Italy",
            code: "ITA",
            flag: "https://crests.football-data.org/784.svg",
          },
          name: "Serie A",
          code: "SA",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/SA.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1505,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 16,
            winner: null,
          },
          numberOfAvailableSeasons: 91,
          lastUpdated: "2022-03-20T09:16:43Z",
        },
        {
          id: 2003,
          area: {
            id: 2163,
            name: "Netherlands",
            code: "NLD",
            flag: "https://crests.football-data.org/8601.svg",
          },
          name: "Eredivisie",
          code: "DED",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/ED.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1494,
            startDate: "2022-08-05",
            endDate: "2023-05-28",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 67,
          lastUpdated: "2022-03-20T09:19:27Z",
        },
        {
          id: 2017,
          area: {
            id: 2187,
            name: "Portugal",
            code: "PRT",
            flag: "https://crests.football-data.org/765.svg",
          },
          name: "Primeira Liga",
          code: "PPL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PPL.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1518,
            startDate: "2022-08-07",
            endDate: "2023-05-28",
            currentMatchday: 14,
            winner: null,
          },
          numberOfAvailableSeasons: 74,
          lastUpdated: "2022-03-20T09:34:09Z",
        },
        {
          id: 2152,
          area: {
            id: 2220,
            name: "South America",
            code: "SAM",
            flag: "https://crests.football-data.org/CLI.svg",
          },
          name: "Copa Libertadores",
          code: "CLI",
          type: "CUP",
          emblem: "https://native-stats.org/assets/flags/SAM.svg",
          plan: "TIER_ONE",
          currentSeason: {
            id: 873,
            startDate: "2022-02-09",
            endDate: "2022-09-06",
            currentMatchday: 6,
            winner: null,
          },
          numberOfAvailableSeasons: 2,
          lastUpdated: "2022-10-31T15:20:09Z",
        },
        {
          id: 2014,
          area: {
            id: 2224,
            name: "Spain",
            code: "ESP",
            flag: "https://crests.football-data.org/760.svg",
          },
          name: "Primera Division",
          code: "PD",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PD.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1504,
            startDate: "2022-08-14",
            endDate: "2023-06-04",
            currentMatchday: 15,
            winner: null,
          },
          numberOfAvailableSeasons: 92,
          lastUpdated: "2022-03-20T09:20:08Z",
        },
        {
          id: 2000,
          area: {
            id: 2267,
            name: "World",
            code: "INT",
            flag: null,
          },
          name: "FIFA World Cup",
          code: "WC",
          type: "CUP",
          emblem: "https://crests.football-data.org/qatar.png",
          plan: "TIER_ONE",
          currentSeason: {
            id: 1382,
            startDate: "2022-11-20",
            endDate: "2022-12-18",
            currentMatchday: 8,
            winner: null,
          },
          numberOfAvailableSeasons: 22,
          lastUpdated: "2022-05-09T19:45:29Z",
        },
      ],
    };
  }

  static CompetitionsStandings(): ICompetitionStandings {
    return {
      filters: {
        season: "2022",
      },
      area: {
        id: 2077,
        name: "Europe",
        code: "EUR",
        flag: "https://crests.football-data.org/EUR.svg",
      },
      competition: {
        id: 2001,
        name: "UEFA Champions League",
        code: "CL",
        type: "CUP",
        emblem: "https://crests.football-data.org/CL.png",
      },
      season: {
        id: 1491,
        startDate: "2022-06-21",
        endDate: "2023-06-10",
        currentMatchday: 6,
        winner: null,
      },
      standings: [
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_A",
          table: [
            {
              position: 1,
              team: {
                id: 113,
                name: "SSC Napoli",
                shortName: "Napoli",
                tla: "NAP",
                crest: "https://crests.football-data.org/113.svg",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 20,
              goalsAgainst: 6,
              goalDifference: 14,
            },
            {
              position: 2,
              team: {
                id: 64,
                name: "Liverpool FC",
                shortName: "Liverpool",
                tla: "LIV",
                crest: "https://crests.football-data.org/64.png",
              },
              playedGames: 6,
              form: null,
              won: 5,
              draw: 0,
              lost: 1,
              points: 15,
              goalsFor: 17,
              goalsAgainst: 6,
              goalDifference: 11,
            },
            {
              position: 3,
              team: {
                id: 678,
                name: "AFC Ajax",
                shortName: "Ajax",
                tla: "AJA",
                crest: "https://crests.football-data.org/678.png",
              },
              playedGames: 6,
              form: null,
              won: 2,
              draw: 0,
              lost: 4,
              points: 6,
              goalsFor: 11,
              goalsAgainst: 16,
              goalDifference: -5,
            },
            {
              position: 4,
              team: {
                id: 5376,
                name: "Rangers FC",
                shortName: "Rangers",
                tla: "RAN",
                crest: "https://crests.football-data.org/5376.png",
              },
              playedGames: 6,
              form: null,
              won: 0,
              draw: 0,
              lost: 6,
              points: 0,
              goalsFor: 2,
              goalsAgainst: 22,
              goalDifference: -20,
            },
          ],
        },
        {
          stage: "GROUP_STAGE",
          type: "TOTAL",
          group: "GROUP_B",
          table: [
            {
              position: 1,
              team: {
                id: 503,
                name: "FC Porto",
                shortName: "Porto",
                tla: "FCP",
                crest: "https://crests.football-data.org/503.png",
              },
              playedGames: 6,
              form: null,
              won: 4,
              draw: 0,
              lost: 2,
              points: 12,
              goalsFor: 12,
              goalsAgainst: 7,
              goalDifference: 5,
            },
            {
              position: 2,
              team: {
                id: 851,
                name: "Club Brugge KV",
                shortName: "Club Brugge",
                tla: "CLU",
                crest: "https://crests.football-data.org/851.svg",
              },
              playedGames: 6,
              form: null,
              won: 3,
              draw: 2,
              lost: 1,
              points: 11,
              goalsFor: 7,
              goalsAgainst: 4,
              goalDifference: 3,
            },
            {
              position: 3,
              team: {
                id: 3,
                name: "Bayer 04 Leverkusen",
                shortName: "Leverkusen",
                tla: "B04",
                crest: "https://crests.football-data.org/3.png",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 4,
              goalsAgainst: 8,
              goalDifference: -4,
            },
            {
              position: 4,
              team: {
                id: 78,
                name: "Club Atlético de Madrid",
                shortName: "Atleti",
                tla: "ATL",
                crest: "https://crests.football-data.org/78.svg",
              },
              playedGames: 6,
              form: null,
              won: 1,
              draw: 2,
              lost: 3,
              points: 5,
              goalsFor: 5,
              goalsAgainst: 9,
              goalDifference: -4,
            },
          ],
        },
      ],
    };
  }

  static CompetitionScorers(): ICompetitionScorers {
    return {
      count: 10,
      filters: {
        season: "2022",
        limit: 10,
      },
      competition: {
        id: 2017,
        name: "Primeira Liga",
        code: "PPL",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PPL.png",
      },
      season: {
        id: 1518,
        startDate: "2022-08-07",
        endDate: "2023-05-28",
        currentMatchday: 14,
        winner: null,
      },
      scorers: [
        {
          player: {
            id: 101431,
            name: "Gonçalo Ramos",
            firstName: "",
            lastName: "Gonçalo Ramos",
            dateOfBirth: "2001-06-20",
            nationality: "Portugal",
            position: "Offence",
            shirtNumber: null,
            lastUpdated: "2022-04-10T09:41:16Z",
          },
          team: {
            id: 1903,
            name: "Sport Lisboa e Benfica",
            shortName: "SL Benfica",
            tla: "BEN",
            crest: "https://crests.football-data.org/1903.png",
            address: "null null null",
            website: "https://www.slbenfica.pt",
            founded: 2020,
            clubColors: null,
            venue: "Estádio do Sport Lisboa e Benfica",
            lastUpdated: "2022-02-19T09:13:16Z",
          },
          goals: 9,
          assists: null,
          penalties: null,
        },
      ],
    };
  }

  static Team(): ITeam {
    return {
      area: {
        id: 2072,
        name: "England",
        code: "ENG",
        flag: "https://crests.football-data.org/770.svg",
      },
      id: 57,
      name: "Arsenal FC",
      shortName: "Arsenal",
      tla: "ARS",
      crest: "https://crests.football-data.org/57.png",
      address: "75 Drayton Park London N5 1BU",
      website: "http://www.arsenal.com",
      founded: 1886,
      clubColors: "Red / White",
      venue: "Emirates Stadium",
      runningCompetitions: [
        {
          id: 2021,
          name: "Premier League",
          code: "PL",
          type: "LEAGUE",
          emblem: "https://crests.football-data.org/PL.png",
        },
        {
          id: 2139,
          name: "Football League Cup",
          code: "FLC",
          type: "CUP",
          emblem: "https://crests.football-data.org/FLC.png",
        },
        {
          id: 2146,
          name: "UEFA Europa League",
          code: "EL",
          type: "CUP",
          emblem: "https://crests.football-data.org/EL.png",
        },
      ],
      coach: {
        id: 11619,
        firstName: "Mikel",
        lastName: null,
        name: "Arteta",
        dateOfBirth: "1982-03-26",
        nationality: "Spain",
        contract: {
          start: null,
          until: null,
        },
      },
      squad: [
        {
          id: 5530,
          name: "Aaron Ramsdale",
          position: "Goalkeeper",
          dateOfBirth: "1998-05-14",
          nationality: "England",
        },
      ],
      staff: [],
      lastUpdated: "2022-02-10T19:48:56Z",
    };
  }
  static CompetitionsTeams(): ICompetitionTeam {
    return {
      count: 20,
      filters: {
        season: "2022",
      },
      competition: {
        id: 2021,
        name: "Premier League",
        code: "PL",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/PL.png",
      },
      season: {
        id: 1490,
        startDate: "2022-08-05",
        endDate: "2023-05-28",
        currentMatchday: 17,
        winner: null,
      },
      teams: [
        {
          area: {
            id: 2072,
            name: "England",
            code: "ENG",
            flag: "https://crests.football-data.org/770.svg",
          },
          id: 57,
          name: "Arsenal FC",
          shortName: "Arsenal",
          tla: "ARS",
          crest: "https://crests.football-data.org/57.png",
          address: "75 Drayton Park London N5 1BU",
          website: "http://www.arsenal.com",
          founded: 1886,
          clubColors: "Red / White",
          venue: "Emirates Stadium",
          runningCompetitions: [
            {
              id: 2021,
              name: "Premier League",
              code: "PL",
              type: "LEAGUE",
              emblem: "https://crests.football-data.org/PL.png",
            },
            {
              id: 2139,
              name: "Football League Cup",
              code: "FLC",
              type: "CUP",
              emblem: "https://crests.football-data.org/FLC.png",
            },
            {
              id: 2146,
              name: "UEFA Europa League",
              code: "EL",
              type: "CUP",
              emblem: "https://crests.football-data.org/EL.png",
            },
          ],
          coach: {
            id: 11619,
            firstName: "Mikel",
            lastName: null,
            name: "Arteta",
            dateOfBirth: "1982-03-26",
            nationality: "Spain",
            contract: {
              start: null,
              until: null,
            },
          },
          squad: [
            {
              id: 5530,
              name: "Aaron Ramsdale",
              position: "Goalkeeper",
              dateOfBirth: "1998-05-14",
              nationality: "England",
            },
            {
              id: 76936,
              name: "Matt Turner",
              position: "Goalkeeper",
              dateOfBirth: "1994-06-24",
              nationality: "United States",
            },
            {
              id: 3244,
              name: "Cédric",
              position: "Defence",
              dateOfBirth: "1991-08-31",
              nationality: "Portugal",
            },
            {
              id: 6154,
              name: "Ben White",
              position: "Defence",
              dateOfBirth: "1997-10-08",
              nationality: "England",
            },
            {
              id: 7784,
              name: "Rob Holding",
              position: "Defence",
              dateOfBirth: "1995-09-20",
              nationality: "England",
            },
            {
              id: 7889,
              name: "Oleksandr Zinchenko",
              position: "Defence",
              dateOfBirth: "1996-12-15",
              nationality: "Ukraine",
            },
            {
              id: 9034,
              name: "Takehiro Tomiyasu",
              position: "Defence",
              dateOfBirth: "1998-11-05",
              nationality: "Japan",
            },
            {
              id: 15615,
              name: "Kieran Tierney",
              position: "Defence",
              dateOfBirth: "1997-06-05",
              nationality: "Scotland",
            },
            {
              id: 23128,
              name: "Gabriel",
              position: "Defence",
              dateOfBirth: "1997-12-19",
              nationality: "Brazil",
            },
            {
              id: 80171,
              name: "William Saliba",
              position: "Defence",
              dateOfBirth: "2001-03-24",
              nationality: "France",
            },
            {
              id: 110,
              name: "Thomas Partey",
              position: "Midfield",
              dateOfBirth: "1993-06-13",
              nationality: "Ghana",
            },
            {
              id: 3477,
              name: "Granit Xhaka",
              position: "Midfield",
              dateOfBirth: "1992-09-27",
              nationality: "Switzerland",
            },
            {
              id: 3755,
              name: "Mohamed El Neny",
              position: "Midfield",
              dateOfBirth: "1992-07-11",
              nationality: "Egypt",
            },
            {
              id: 7427,
              name: "Martin Ødegaard",
              position: "Midfield",
              dateOfBirth: "1998-12-17",
              nationality: "Norway",
            },
            {
              id: 8862,
              name: "Albert Sambi Lokonga",
              position: "Midfield",
              dateOfBirth: "1999-10-22",
              nationality: "Belgium",
            },
            {
              id: 85570,
              name: "Emile Smith Rowe",
              position: "Midfield",
              dateOfBirth: "2000-07-28",
              nationality: "England",
            },
            {
              id: 112948,
              name: "Fabio Vieira",
              position: "Midfield",
              dateOfBirth: "2000-05-30",
              nationality: "Portugal",
            },
            {
              id: 169277,
              name: "Marquinhos",
              position: "Midfield",
              dateOfBirth: "2003-04-07",
              nationality: "Brazil",
            },
            {
              id: 3236,
              name: "Gabriel Jesus",
              position: "Offence",
              dateOfBirth: "1997-04-03",
              nationality: "Brazil",
            },
            {
              id: 7799,
              name: "Reiss Nelson",
              position: "Offence",
              dateOfBirth: "1999-12-10",
              nationality: "England",
            },
            {
              id: 7800,
              name: "Eddie Nketiah",
              position: "Offence",
              dateOfBirth: "1999-05-30",
              nationality: "England",
            },
            {
              id: 61450,
              name: "Martinelli",
              position: "Offence",
              dateOfBirth: "2001-06-18",
              nationality: "Brazil",
            },
            {
              id: 99813,
              name: "Bukayo Saka",
              position: "Offence",
              dateOfBirth: "2001-09-05",
              nationality: "England",
            },
          ],
          staff: [],
          lastUpdated: "2022-02-10T19:48:56Z",
        },
      ],
    };
  }

  static CompetitionsMatches(): ICompetitionMatches {
    return {
      filters: {
        season: "2022",
      },
      resultSet: {
        count: 6,
        first: "2022-12-28",
        last: "2022-12-28",
        played: 0,
      },
      competition: {
        id: 2015,
        name: "Ligue 1",
        code: "FL1",
        type: "LEAGUE",
        emblem: "https://crests.football-data.org/FL1.png",
      },
      matches: [
        {
          area: {
            id: 2081,
            name: "France",
            code: "FRA",
            flag: "https://crests.football-data.org/773.svg",
          },
          competition: {
            id: 2015,
            name: "Ligue 1",
            code: "FL1",
            type: "LEAGUE",
            emblem: "https://crests.football-data.org/FL1.png",
          },
          season: {
            id: 1497,
            startDate: "2022-08-07",
            endDate: "2023-06-03",
            currentMatchday: 16,
            winner: null,
          },
          id: 417109,
          utcDate: "2022-12-28T14:00:00Z",
          status: "TIMED",
          matchday: 16,
          stage: "REGULAR_SEASON",
          group: null,
          lastUpdated: "2022-11-19T16:20:09Z",
          homeTeam: {
            id: 531,
            name: "ES Troyes AC",
            shortName: "Troyes",
            tla: "ETR",
            crest: "https://crests.football-data.org/531.svg",
          },
          awayTeam: {
            id: 543,
            name: "FC Nantes",
            shortName: "Nantes",
            tla: "NAN",
            crest: "https://crests.football-data.org/543.svg",
          },
          score: {
            winner: null,
            duration: "REGULAR",
            fullTime: {
              home: null,
              away: null,
            },
            halfTime: {
              home: null,
              away: null,
            },
          },
          odds: {
            homeWin: 2.09,
            draw: 3.66,
            awayWin: 3.76,
          },
          referees: [],
        },
      ],
    };
  }

  // static CompetitionsSelect() {
  //   return {
  //     area: {
  //       id: 2072,
  //       name: "England",
  //       code: "ENG",
  //       flag: "https://crests.football-data.org/770.svg",
  //     },
  //     id: 2021,
  //     name: "Premier League",
  //     code: "PL",
  //     type: "LEAGUE",
  //     emblem: "https://crests.football-data.org/PL.png",
  //     currentSeason: {
  //       id: 1490,
  //       startDate: "2022-08-05",
  //       endDate: "2023-05-28",
  //       currentMatchday: 17,
  //       winner: null,
  //     },
  //     seasons: [
  //       {
  //         id: 1490,
  //         startDate: "2022-08-05",
  //         endDate: "2023-05-28",
  //         currentMatchday: 17,
  //         winner: null,
  //       },
  //       {
  //         id: 733,
  //         startDate: "2021-08-13",
  //         endDate: "2022-05-22",
  //         currentMatchday: 38,
  //         winner: null,
  //       },
  //       {
  //         id: 619,
  //         startDate: "2020-09-12",
  //         endDate: "2021-05-23",
  //         currentMatchday: 38,
  //         winner: {
  //           id: 65,
  //           name: "Manchester City FC",
  //           shortName: "Man City",
  //           tla: "MCI",
  //           crest: "https://crests.football-data.org/65.png",
  //           address: "SportCity Manchester M11 3FF",
  //           website: "https://www.mancity.com",
  //           founded: 1880,
  //           clubColors: "Sky Blue / White",
  //           venue: "Etihad Stadium",
  //           lastUpdated: "2022-02-10T19:48:37Z",
  //         },
  //       },
  //       {
  //         id: 468,
  //         startDate: "2019-08-09",
  //         endDate: "2020-07-26",
  //         currentMatchday: 38,
  //         winner: {
  //           id: 64,
  //           name: "Liverpool FC",
  //           shortName: "Liverpool",
  //           tla: "LIV",
  //           crest: "https://crests.football-data.org/64.png",
  //           address: "Anfield Road Liverpool L4 0TH",
  //           website: "http://www.liverpoolfc.tv",
  //           founded: 1892,
  //           clubColors: "Red / White",
  //           venue: "Anfield",
  //           lastUpdated: "2022-02-10T19:30:22Z",
  //         },
  //       },
  //       {
  //         id: 151,
  //         startDate: "2018-08-10",
  //         endDate: "2019-05-12",
  //         currentMatchday: 38,
  //         winner: {
  //           id: 65,
  //           name: "Manchester City FC",
  //           shortName: "Man City",
  //           tla: "MCI",
  //           crest: "https://crests.football-data.org/65.png",
  //           address: "SportCity Manchester M11 3FF",
  //           website: "https://www.mancity.com",
  //           founded: 1880,
  //           clubColors: "Sky Blue / White",
  //           venue: "Etihad Stadium",
  //           lastUpdated: "2022-02-10T19:48:37Z",
  //         },
  //       },
  //       {
  //         id: 23,
  //         startDate: "2017-08-11",
  //         endDate: "2018-05-13",
  //         currentMatchday: 38,
  //         winner: {
  //           id: 65,
  //           name: "Manchester City FC",
  //           shortName: "Man City",
  //           tla: "MCI",
  //           crest: "https://crests.football-data.org/65.png",
  //           address: "SportCity Manchester M11 3FF",
  //           website: "https://www.mancity.com",
  //           founded: 1880,
  //           clubColors: "Sky Blue / White",
  //           venue: "Etihad Stadium",
  //           lastUpdated: "2022-02-10T19:48:37Z",
  //         },
  //       },
  //       {
  //         id: 256,
  //         startDate: "2016-08-13",
  //         endDate: "2017-05-21",
  //         currentMatchday: null,
  //         winner: {
  //           id: 61,
  //           name: "Chelsea FC",
  //           shortName: "Chelsea",
  //           tla: "CHE",
  //           crest: "https://crests.football-data.org/61.png",
  //           address: "Fulham Road London SW6 1HS",
  //           website: "http://www.chelseafc.com",
  //           founded: 1905,
  //           clubColors: "Royal Blue / White",
  //           venue: "Stamford Bridge",
  //           lastUpdated: "2022-02-10T19:24:40Z",
  //         },
  //       },
  //       {
  //         id: 257,
  //         startDate: "2015-08-08",
  //         endDate: "2016-05-17",
  //         currentMatchday: null,
  //         winner: {
  //           id: 338,
  //           name: "Leicester City FC",
  //           shortName: "Leicester City",
  //           tla: "LEI",
  //           crest: "https://crests.football-data.org/338.png",
  //           address: "The Walkers Stadium, Filbert Way Leicester LE2 7FL",
  //           website: "http://www.lcfc.com",
  //           founded: 1884,
  //           clubColors: "Royal Blue / White",
  //           venue: "King Power Stadium",
  //           lastUpdated: "2022-02-10T19:48:23Z",
  //         },
  //       },
  //       {
  //         id: 258,
  //         startDate: "2014-08-16",
  //         endDate: "2015-05-24",
  //         currentMatchday: null,
  //         winner: {
  //           id: 61,
  //           name: "Chelsea FC",
  //           shortName: "Chelsea",
  //           tla: "CHE",
  //           crest: "https://crests.football-data.org/61.png",
  //           address: "Fulham Road London SW6 1HS",
  //           website: "http://www.chelseafc.com",
  //           founded: 1905,
  //           clubColors: "Royal Blue / White",
  //           venue: "Stamford Bridge",
  //           lastUpdated: "2022-02-10T19:24:40Z",
  //         },
  //       },
  //       {
  //         id: 259,
  //         startDate: "2013-08-17",
  //         endDate: "2014-05-11",
  //         currentMatchday: null,
  //         winner: {
  //           id: 65,
  //           name: "Manchester City FC",
  //           shortName: "Man City",
  //           tla: "MCI",
  //           crest: "https://crests.football-data.org/65.png",
  //           address: "SportCity Manchester M11 3FF",
  //           website: "https://www.mancity.com",
  //           founded: 1880,
  //           clubColors: "Sky Blue / White",
  //           venue: "Etihad Stadium",
  //           lastUpdated: "2022-02-10T19:48:37Z",
  //         },
  //       },
  //       {
  //         id: 260,
  //         startDate: "2012-08-18",
  //         endDate: "2013-05-19",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 261,
  //         startDate: "2011-08-13",
  //         endDate: "2012-05-13",
  //         currentMatchday: null,
  //         winner: {
  //           id: 65,
  //           name: "Manchester City FC",
  //           shortName: "Man City",
  //           tla: "MCI",
  //           crest: "https://crests.football-data.org/65.png",
  //           address: "SportCity Manchester M11 3FF",
  //           website: "https://www.mancity.com",
  //           founded: 1880,
  //           clubColors: "Sky Blue / White",
  //           venue: "Etihad Stadium",
  //           lastUpdated: "2022-02-10T19:48:37Z",
  //         },
  //       },
  //       {
  //         id: 262,
  //         startDate: "2010-08-14",
  //         endDate: "2011-05-22",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 263,
  //         startDate: "2009-08-15",
  //         endDate: "2010-05-09",
  //         currentMatchday: null,
  //         winner: {
  //           id: 61,
  //           name: "Chelsea FC",
  //           shortName: "Chelsea",
  //           tla: "CHE",
  //           crest: "https://crests.football-data.org/61.png",
  //           address: "Fulham Road London SW6 1HS",
  //           website: "http://www.chelseafc.com",
  //           founded: 1905,
  //           clubColors: "Royal Blue / White",
  //           venue: "Stamford Bridge",
  //           lastUpdated: "2022-02-10T19:24:40Z",
  //         },
  //       },
  //       {
  //         id: 264,
  //         startDate: "2008-08-16",
  //         endDate: "2009-05-24",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 265,
  //         startDate: "2007-08-11",
  //         endDate: "2008-05-11",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 266,
  //         startDate: "2006-08-19",
  //         endDate: "2007-05-13",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 267,
  //         startDate: "2005-08-13",
  //         endDate: "2006-05-07",
  //         currentMatchday: null,
  //         winner: {
  //           id: 61,
  //           name: "Chelsea FC",
  //           shortName: "Chelsea",
  //           tla: "CHE",
  //           crest: "https://crests.football-data.org/61.png",
  //           address: "Fulham Road London SW6 1HS",
  //           website: "http://www.chelseafc.com",
  //           founded: 1905,
  //           clubColors: "Royal Blue / White",
  //           venue: "Stamford Bridge",
  //           lastUpdated: "2022-02-10T19:24:40Z",
  //         },
  //       },
  //       {
  //         id: 268,
  //         startDate: "2004-08-14",
  //         endDate: "2005-05-15",
  //         currentMatchday: null,
  //         winner: {
  //           id: 61,
  //           name: "Chelsea FC",
  //           shortName: "Chelsea",
  //           tla: "CHE",
  //           crest: "https://crests.football-data.org/61.png",
  //           address: "Fulham Road London SW6 1HS",
  //           website: "http://www.chelseafc.com",
  //           founded: 1905,
  //           clubColors: "Royal Blue / White",
  //           venue: "Stamford Bridge",
  //           lastUpdated: "2022-02-10T19:24:40Z",
  //         },
  //       },
  //       {
  //         id: 269,
  //         startDate: "2003-08-16",
  //         endDate: "2004-05-15",
  //         currentMatchday: null,
  //         winner: {
  //           id: 57,
  //           name: "Arsenal FC",
  //           shortName: "Arsenal",
  //           tla: "ARS",
  //           crest: "https://crests.football-data.org/57.png",
  //           address: "75 Drayton Park London N5 1BU",
  //           website: "http://www.arsenal.com",
  //           founded: 1886,
  //           clubColors: "Red / White",
  //           venue: "Emirates Stadium",
  //           lastUpdated: "2022-02-10T19:48:56Z",
  //         },
  //       },
  //       {
  //         id: 270,
  //         startDate: "2002-08-17",
  //         endDate: "2003-05-11",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 271,
  //         startDate: "2001-08-18",
  //         endDate: "2002-05-11",
  //         currentMatchday: null,
  //         winner: {
  //           id: 57,
  //           name: "Arsenal FC",
  //           shortName: "Arsenal",
  //           tla: "ARS",
  //           crest: "https://crests.football-data.org/57.png",
  //           address: "75 Drayton Park London N5 1BU",
  //           website: "http://www.arsenal.com",
  //           founded: 1886,
  //           clubColors: "Red / White",
  //           venue: "Emirates Stadium",
  //           lastUpdated: "2022-02-10T19:48:56Z",
  //         },
  //       },
  //       {
  //         id: 272,
  //         startDate: "2000-08-19",
  //         endDate: "2001-05-19",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 273,
  //         startDate: "1999-08-07",
  //         endDate: "2000-05-14",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 274,
  //         startDate: "1998-08-15",
  //         endDate: "1999-05-16",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 275,
  //         startDate: "1997-08-09",
  //         endDate: "1998-05-10",
  //         currentMatchday: null,
  //         winner: {
  //           id: 57,
  //           name: "Arsenal FC",
  //           shortName: "Arsenal",
  //           tla: "ARS",
  //           crest: "https://crests.football-data.org/57.png",
  //           address: "75 Drayton Park London N5 1BU",
  //           website: "http://www.arsenal.com",
  //           founded: 1886,
  //           clubColors: "Red / White",
  //           venue: "Emirates Stadium",
  //           lastUpdated: "2022-02-10T19:48:56Z",
  //         },
  //       },
  //       {
  //         id: 276,
  //         startDate: "1996-08-17",
  //         endDate: "1997-05-11",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 277,
  //         startDate: "1995-08-19",
  //         endDate: "1996-05-04",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 254,
  //         startDate: "1994-08-20",
  //         endDate: "1995-05-14",
  //         currentMatchday: null,
  //         winner: {
  //           id: 59,
  //           name: "Blackburn Rovers FC",
  //           shortName: "Blackburn",
  //           tla: "BLA",
  //           crest: "https://crests.football-data.org/59.png",
  //           address: "Ewood Park Blackburn BB2 4JF",
  //           website: "http://www.rovers.co.uk",
  //           founded: 1874,
  //           clubColors: "Blue / White",
  //           venue: "Ewood Park",
  //           lastUpdated: "2022-02-19T08:50:27Z",
  //         },
  //       },
  //       {
  //         id: 255,
  //         startDate: "1993-08-14",
  //         endDate: "1994-05-08",
  //         currentMatchday: null,
  //         winner: {
  //           id: 66,
  //           name: "Manchester United FC",
  //           shortName: "Man United",
  //           tla: "MUN",
  //           crest: "https://crests.football-data.org/66.png",
  //           address: "Sir Matt Busby Way Manchester M16 0RA",
  //           website: "http://www.manutd.com",
  //           founded: 1878,
  //           clubColors: "Red / White",
  //           venue: "Old Trafford",
  //           lastUpdated: "2022-02-10T19:27:46Z",
  //         },
  //       },
  //       {
  //         id: 818,
  //         startDate: "1992-08-13",
  //         endDate: "1993-05-09",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 819,
  //         startDate: "1991-08-15",
  //         endDate: "1992-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 820,
  //         startDate: "1990-08-23",
  //         endDate: "1991-05-18",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 821,
  //         startDate: "1989-08-17",
  //         endDate: "1990-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 822,
  //         startDate: "1988-08-25",
  //         endDate: "1989-05-24",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 913,
  //         startDate: "1987-08-13",
  //         endDate: "1988-05-13",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 823,
  //         startDate: "1986-08-21",
  //         endDate: "1987-05-09",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 824,
  //         startDate: "1985-08-15",
  //         endDate: "1986-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 825,
  //         startDate: "1984-08-23",
  //         endDate: "1985-05-26",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 826,
  //         startDate: "1983-08-25",
  //         endDate: "1984-05-15",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 827,
  //         startDate: "1982-08-26",
  //         endDate: "1983-05-12",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 828,
  //         startDate: "1981-08-27",
  //         endDate: "1982-05-19",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 829,
  //         startDate: "1980-08-14",
  //         endDate: "1981-05-17",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 830,
  //         startDate: "1979-08-16",
  //         endDate: "1980-05-17",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 831,
  //         startDate: "1978-08-17",
  //         endDate: "1979-05-16",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 832,
  //         startDate: "1977-08-18",
  //         endDate: "1978-05-07",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 833,
  //         startDate: "1976-08-19",
  //         endDate: "1977-05-22",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 834,
  //         startDate: "1975-08-14",
  //         endDate: "1976-05-02",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 835,
  //         startDate: "1974-08-15",
  //         endDate: "1975-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 836,
  //         startDate: "1973-08-23",
  //         endDate: "1974-05-09",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 837,
  //         startDate: "1972-08-10",
  //         endDate: "1973-05-07",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 838,
  //         startDate: "1971-08-12",
  //         endDate: "1972-05-09",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 912,
  //         startDate: "1970-08-13",
  //         endDate: "1971-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 839,
  //         startDate: "1969-08-07",
  //         endDate: "1970-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 914,
  //         startDate: "1968-08-08",
  //         endDate: "1969-05-15",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 915,
  //         startDate: "1967-08-17",
  //         endDate: "1968-05-19",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 916,
  //         startDate: "1966-08-18",
  //         endDate: "1967-05-14",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 925,
  //         startDate: "1965-08-19",
  //         endDate: "1966-05-17",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 924,
  //         startDate: "1964-08-20",
  //         endDate: "1965-04-26",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 923,
  //         startDate: "1963-08-22",
  //         endDate: "1964-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 922,
  //         startDate: "1962-08-16",
  //         endDate: "1963-05-19",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 921,
  //         startDate: "1961-08-17",
  //         endDate: "1962-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 920,
  //         startDate: "1960-08-18",
  //         endDate: "1961-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 919,
  //         startDate: "1959-08-20",
  //         endDate: "1960-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 918,
  //         startDate: "1958-08-21",
  //         endDate: "1959-05-02",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 917,
  //         startDate: "1957-08-22",
  //         endDate: "1958-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 926,
  //         startDate: "1956-08-16",
  //         endDate: "1957-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 935,
  //         startDate: "1955-08-18",
  //         endDate: "1956-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 936,
  //         startDate: "1954-08-19",
  //         endDate: "1955-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 937,
  //         startDate: "1953-08-17",
  //         endDate: "1954-04-24",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 938,
  //         startDate: "1952-08-21",
  //         endDate: "1953-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 939,
  //         startDate: "1951-08-16",
  //         endDate: "1952-05-01",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 940,
  //         startDate: "1950-08-17",
  //         endDate: "1951-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 934,
  //         startDate: "1949-08-18",
  //         endDate: "1950-05-04",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 933,
  //         startDate: "1948-08-19",
  //         endDate: "1949-05-07",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 932,
  //         startDate: "1947-08-21",
  //         endDate: "1948-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 931,
  //         startDate: "1946-08-29",
  //         endDate: "1947-06-12",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 930,
  //         startDate: "1938-08-25",
  //         endDate: "1939-05-04",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 928,
  //         startDate: "1937-08-26",
  //         endDate: "1938-05-05",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 927,
  //         startDate: "1936-08-27",
  //         endDate: "1937-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 929,
  //         startDate: "1935-08-29",
  //         endDate: "1936-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 963,
  //         startDate: "1934-08-23",
  //         endDate: "1935-05-02",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 950,
  //         startDate: "1933-08-24",
  //         endDate: "1934-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 949,
  //         startDate: "1932-08-25",
  //         endDate: "1933-05-04",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 948,
  //         startDate: "1931-08-27",
  //         endDate: "1932-05-05",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 947,
  //         startDate: "1930-08-28",
  //         endDate: "1931-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 946,
  //         startDate: "1929-08-29",
  //         endDate: "1930-05-01",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 945,
  //         startDate: "1928-08-23",
  //         endDate: "1929-05-02",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 944,
  //         startDate: "1927-08-25",
  //         endDate: "1928-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 943,
  //         startDate: "1926-08-26",
  //         endDate: "1927-05-05",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 942,
  //         startDate: "1925-08-27",
  //         endDate: "1926-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 941,
  //         startDate: "1924-08-28",
  //         endDate: "1925-04-30",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 951,
  //         startDate: "1923-08-23",
  //         endDate: "1924-05-01",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 952,
  //         startDate: "1922-08-24",
  //         endDate: "1923-05-03",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 962,
  //         startDate: "1921-08-25",
  //         endDate: "1922-05-04",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 961,
  //         startDate: "1920-08-26",
  //         endDate: "1921-05-05",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 960,
  //         startDate: "1919-08-28",
  //         endDate: "1920-04-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 957,
  //         startDate: "1914-08-30",
  //         endDate: "1915-04-26",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 958,
  //         startDate: "1913-08-30",
  //         endDate: "1914-04-25",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 955,
  //         startDate: "1912-08-31",
  //         endDate: "1913-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 959,
  //         startDate: "1911-08-31",
  //         endDate: "1912-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 956,
  //         startDate: "1910-08-30",
  //         endDate: "1911-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 953,
  //         startDate: "1909-08-30",
  //         endDate: "1910-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 954,
  //         startDate: "1908-08-30",
  //         endDate: "1909-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 964,
  //         startDate: "1907-08-31",
  //         endDate: "1908-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 965,
  //         startDate: "1906-08-30",
  //         endDate: "1907-04-25",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 966,
  //         startDate: "1905-08-31",
  //         endDate: "1906-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 967,
  //         startDate: "1904-08-30",
  //         endDate: "1905-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 968,
  //         startDate: "1903-08-30",
  //         endDate: "1904-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 969,
  //         startDate: "1902-08-30",
  //         endDate: "1903-04-25",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 970,
  //         startDate: "1901-08-31",
  //         endDate: "1902-04-26",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 971,
  //         startDate: "1900-08-30",
  //         endDate: "1901-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 972,
  //         startDate: "1899-08-31",
  //         endDate: "1900-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 973,
  //         startDate: "1898-08-30",
  //         endDate: "1899-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 983,
  //         startDate: "1897-08-30",
  //         endDate: "1898-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 984,
  //         startDate: "1896-08-30",
  //         endDate: "1897-04-24",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 975,
  //         startDate: "1895-08-31",
  //         endDate: "1896-04-27",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 976,
  //         startDate: "1894-08-30",
  //         endDate: "1895-04-22",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 981,
  //         startDate: "1893-08-31",
  //         endDate: "1894-04-21",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 979,
  //         startDate: "1892-09-01",
  //         endDate: "1893-04-15",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 985,
  //         startDate: "1891-09-03",
  //         endDate: "1892-04-28",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 977,
  //         startDate: "1890-09-04",
  //         endDate: "1891-04-16",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 978,
  //         startDate: "1889-09-05",
  //         endDate: "1890-03-29",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //       {
  //         id: 1040,
  //         startDate: "1888-09-06",
  //         endDate: "1889-04-18",
  //         currentMatchday: null,
  //         winner: null,
  //       },
  //     ],
  //     lastUpdated: "2022-03-20T08:58:54Z",
  //   };
  // }
}
